name: Build and Release Nono

on:
  workflow_dispatch: {}                 # <-- lets you click “Run workflow”
  push:
    tags:
      - "v*.*.*"                        # <-- runs when you push v0.1.0 etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nono-${{ matrix.os }}
          path: src-tauri/target/release/bundle
