name: "Build and Release Nono"

on:
  push:
    tags:
      - "v*.*.*"   # runs when you push a tag like v0.1.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nono-${{ matrix.os }}
          path: src-tauri/target/release/bundle

